[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 14.0

[window]
startup_mode = "Fullscreen"
padding = { x = 10, y = 10 }

[shell]
program = "/bin/zsh"
args = ["-c", "ssh PPVM"]
