[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 12

[terminal.shell]
program = "/bin/zsh"
args = ["-lc", "tmux"]

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
opacity = 0.95
blur = true
startup_mode = "Maximized"

[colors.primary]
background = "#0d1117"
foreground = "#e6edf3"

[colors.normal]
black   = "#484f58"
red     = "#ff7b72"
green   = "#3fb950"
yellow  = "#d29922"
blue    = "#58a6ff"
magenta = "#bc8cff"
cyan    = "#39c5cf"
white   = "#b1bac4"

[colors.bright]
black   = "#6e7681"
red     = "#ffa198"
green   = "#56d364"
yellow  = "#e3b341"
blue    = "#79c0ff"
magenta = "#d2a8ff"
cyan    = "#56d4dd"
white   = "#f0f6fc"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\x1b\r"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"  # macOS default. Use "xdg-open" on Linux.
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Shift"

