[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 12

[terminal.shell]
program = "/bin/zsh"
args = ["-lc", "tmux"]

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
opacity = 0.95
blur = true
startup_mode = "Maximized"

[colors.primary]
background = "#002b36"
foreground = "#839496"

[colors.cursor]
text = "#002b36"
cursor = "#93a1a1"

[colors.selection]
text = "#93a1a1"
background = "#073642"

[colors.normal]
black   = "#073642"
red     = "#dc322f"
green   = "#859900"
yellow  = "#b58900"
blue    = "#268bd2"
magenta = "#d33682"
cyan    = "#2aa198"
white   = "#eee8d5"

[colors.bright]
black   = "#002b36"
red     = "#cb4b16"
green   = "#586e75"
yellow  = "#657b83"
blue    = "#839496"
magenta = "#6c71c4"
cyan    = "#93a1a1"
white   = "#fdf6e3"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\x1b\r"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"  # macOS default. Use "xdg-open" on Linux.
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Shift"

