#!/usr/bin/env zsh

# zsh
rm ~/.zshrc
ln -s $(pwd)/zshrc.sh ~/.zshrc

# tmux
rm ~/.tmux.conf
ln -s $(pwd)/tmux.conf ~/.tmux.conf

# neovim (vim)
rm ~/.config/nvim/init.vim
ln -s $(pwd)/neovim.vim ~/.config/nvim/init.vim

# neovim (lua)
rm ~/.config/nvim/init.lua
ln -s $(pwd)/neovim.lua ~/.config/nvim/init.lua

# gitconfig
rm ~/.gitconfig
ln -s $(pwd)/gitconfig ~/.gitconfig

# php
rm $(asdf where php)/conf.d/php.ini
ln -s $(pwd)/php.ini $(asdf where php)/conf.d/php.ini

