#!/usr/bin/env zsh

# zsh
rm ~/.zshrc
ln -s $(pwd)/zshrc.sh ~/.zshrc

# tmux
rm ~/.tmux.conf
ln -s $(pwd)/tmux.conf ~/.tmux.conf

# neovim
rm -rf ~/.config/nvim/lua
rm ~/.config/nvim/init.lua
ln -s $(pwd)/nvim/lua ~/.config/nvim/lua
ln -s $(pwd)/nvim/init.lua ~/.config/nvim/init.lua

# gitconfig
rm ~/.gitconfig
ln -s $(pwd)/gitconfig ~/.gitconfig

