# vim:ft=kitty

## name:     Gruvbox Dark
## author:   morhetz (adapted)
## license:  MIT
## upstream: https://github.com/morhetz/gruvbox

# The basic colors
foreground              #ebdbb2
background              #282828
selection_foreground    #282828
selection_background    #ebdbb2

# Cursor colors
cursor                  #ebdbb2
cursor_text_color       #282828

# URL underline color when hovering with mouse
url_color               #83a598

# Kitty window border colors
active_border_color     #b8bb26
inactive_border_color   #504945
bell_border_color       #fabd2f

# OS Window titlebar colors
wayland_titlebar_color  #282828
macos_titlebar_color    #282828

# Tab bar colors
active_tab_foreground   #282828
active_tab_background   #83a598
inactive_tab_foreground #a89984
inactive_tab_background #3c3836
tab_bar_background      #282828

# Colors for marks (marked text in the terminal)
mark1_foreground #282828
mark1_background #83a598
mark2_foreground #282828
mark2_background #d3869b
mark3_foreground #282828
mark3_background #8ec07c

# The 16 terminal colors

# black
color0  #282828
color8  #928374

# red
color1  #cc241d
color9  #fb4934

# green
color2  #98971a
color10 #b8bb26

# yellow
color3  #d79921
color11 #fabd2f

# blue
color4  #458588
color12 #83a598

# magenta
color5  #b16286
color13 #d3869b

# cyan
color6  #689d6a
color14 #8ec07c

# white
color7  #a89984
color15 #ebdbb2
