# vim:ft=kitty

## name:     Gruvbox Light
## author:   morhetz (adapted)
## license:  MIT
## upstream: https://github.com/morhetz/gruvbox

# The basic colors
foreground              #3c3836
background              #fbf1c7
selection_foreground    #fbf1c7
selection_background    #3c3836

# Cursor colors
cursor                  #3c3836
cursor_text_color       #fbf1c7

# URL underline color when hovering with mouse
url_color               #076678

# Kitty window border colors
active_border_color     #79740e
inactive_border_color   #d5c4a1
bell_border_color       #b57614

# OS Window titlebar colors
wayland_titlebar_color  #fbf1c7
macos_titlebar_color    #fbf1c7

# Tab bar colors
active_tab_foreground   #fbf1c7
active_tab_background   #076678
inactive_tab_foreground #7c6f64
inactive_tab_background #ebdbb2
tab_bar_background      #fbf1c7

# Colors for marks (marked text in the terminal)
mark1_foreground #fbf1c7
mark1_background #076678
mark2_foreground #fbf1c7
mark2_background #8f3f71
mark3_foreground #fbf1c7
mark3_background #427b58

# The 16 terminal colors

# black
color0  #fbf1c7
color8  #928374

# red
color1  #cc241d
color9  #9d0006

# green
color2  #98971a
color10 #79740e

# yellow
color3  #d79921
color11 #b57614

# blue
color4  #458588
color12 #076678

# magenta
color5  #b16286
color13 #8f3f71

# cyan
color6  #689d6a
color14 #427b58

# white
color7  #7c6f64
color15 #3c3836
