base = "ocean"
syntax = "base16-ocean.dark"

[ui]
toc_bg = "#1d2021"
toc_border = "#504945"
content_bg = "#282828"
scrollbar_hover = "#fabd2f"
status_bg = "#1d2021"
status_separator = "#928374"
status_brand_fg = "#282828"
status_brand_bg = "#fabd2f"
status_filename_fg = "#ebdbb2"
status_filename_bg = "#3c3836"
status_watch_fg = "#b8bb26"
status_watch_bg = "#32361a"
status_reloaded_fg = "#282828"
status_reloaded_bg = "#b8bb26"
status_search_fg = "#fabd2f"
status_search_bg = "#3c3836"
status_success_fg = "#b8bb26"
status_success_bg = "#32361a"
status_warning_fg = "#fabd2f"
status_error_fg = "#fb4934"
status_error_bg = "#3c1f1e"
status_shortcut_fg = "#928374"
status_percent_fg = "#fabd2f"
toc_header_fg = "#928374"
toc_active_bg = "#3c3836"
toc_inactive_bg = "#1d2021"
toc_accent = "#fe8019"
toc_index_inactive = "#665c54"
toc_primary_active = "#fbf1c7"
toc_primary_inactive = "#d5c4a1"
toc_secondary_inactive = "#665c54"
toc_secondary_text_active = "#ebdbb2"
toc_secondary_text_inactive = "#928374"

[markdown]
search_highlight_bg = "#665c54"
code_gutter = "#665c54"
blockquote_marker = "#928374"
list_level_1 = "#b8bb26"
list_level_2 = "#83a598"
list_level_3 = "#d3869b"
ordered_list = "#fabd2f"
table_border = "#665c54"
table_separator = "#504945"
table_header = "#fabd2f"
table_cell = "#ebdbb2"
heading_1 = "#fabd2f"
heading_2 = "#b8bb26"
heading_3 = "#83a598"
heading_4 = "#d3869b"
heading_other = "#fe8019"
heading_underline = "#504945"
code_frame = "#665c54"
code_label = "#928374"
inline_code_fg = "#fe8019"
inline_code_bg = "#3c3836"
rule = "#504945"
link_icon = "#83a598"
link_text = "#83a598"
blockquote_text = "#d5c4a1"
text = "#ebdbb2"
strong_text = "#fbf1c7"
latex_inline_fg = "#d3869b"
latex_inline_bg = "#3c3836"
latex_block_fg = "#d3869b"
mermaid_keyword = "#fe8019"
mermaid_arrow = "#83a598"
mermaid_label = "#b8bb26"
mermaid_block_fg = "#ebdbb2"
