gui:
  theme:
    activeBorderColor:
      - '#83a598'
      - bold
    inactiveBorderColor:
      - '#504945'
    searchingActiveBorderColor:
      - '#fabd2f'
      - bold
    optionsTextColor:
      - '#83a598'
    selectedLineBgColor:
      - '#3c3836'
    inactiveViewSelectedLineBgColor:
      - '#3c3836'
    cherryPickedCommitFgColor:
      - '#83a598'
    cherryPickedCommitBgColor:
      - '#504945'
    markedBaseCommitFgColor:
      - '#8ec07c'
    markedBaseCommitBgColor:
      - '#504945'
    unstagedChangesColor:
      - '#fb4934'
    defaultFgColor:
      - '#ebdbb2'
