"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 3000

# GitHub Dark Default palette
palette = "solarized_dark"

[palettes.solarized_dark]
bg = "#002b36"
fg = "#839496"
fg_muted = "#586e75"
fg_subtle = "#586e75"
red = "#dc322f"
bright_red = "#cb4b16"
orange = "#cb4b16"
yellow = "#b58900"
bright_yellow = "#657b83"
green = "#859900"
bright_green = "#586e75"
cyan = "#2aa198"
bright_cyan = "#93a1a1"
blue = "#268bd2"
bright_blue = "#839496"
purple = "#6c71c4"
magenta = "#d33682"

[username]
disabled = true

[hostname]
disabled = false

[kubernetes]
disabled = true

[aws]
disabled = true

[directory]
truncation_length = 2
truncate_to_repo = false
style = "bold fg"

[package]
disabled = true

[docker_context]
disabled = true

[cmd_duration]
disabled = false
min_time = 0
show_milliseconds = true
style = "yellow"

[git_branch]
style = "purple"

[git_status]
disabled = true

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[nodejs]
detect_files = ["package.json", ".node-version", ".nvmrc"]
detect_folders = ["node_modules"]
detect_extensions = []

[gcloud]
disabled = true

